theme = "dracula"

[editor]
line-number = "relative"
mouse = true
true-color = true
cursorline = true
rulers = [80]
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"S-up" = "jump_view_up"
"S-down" = "jump_view_down"
"S-left" = "jump_view_left"
"S-right" = "jump_view_right"
"A-left" = ":bp"
"A-right" = ":bn"
"C-q" = ":bc"
"C-s" = ":w"

[keys.insert]
j = { j = "normal_mode" } # Maps `jj` to exit insert mode
"left" = "move_char_left"
"down" = "move_line_down"
"up" = "move_line_up"
"right" = "move_char_right"

[editor.file-picker]
hidden = false
git-ignore = false

# Whitespace config
[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"
tabpad = "none"

[editor.whitespace.characters]
# space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
# newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "╎", "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

