theme = "gruvbox_custom"

[editor]
line-number = "relative"
mouse = true
true-color = true

[keys.normal]
"S-up" = "jump_view_up"
"S-down" = "jump_view_down"
"S-left" = "jump_view_left"
"S-right" = "jump_view_right"
"C-s" = ":w"

[keys.insert]
j = { j = "normal_mode" } # Maps `jj` to exit insert mode
