theme = "default"

[editor]
line-number = "relative"
mouse = true
true-color = true

[keys.normal]
"S-up" = "jump_view_up"
"S-down" = "jump_view_down"
"S-left" = "jump_view_left"
"S-right" = "jump_view_right"
"C-s" = ":w"

[keys.insert]
j = { j = "normal_mode" } # Maps `jj` to exit insert mode
"left" = "move_char_left"
"down" = "move_line_down"
"up" = "move_line_up"
"right" = "move_char_right"

[editor.file-picker]
hidden = false
git-ignore = false