require('plugin_config.lualine')
require('plugin_config.comment')
require('plugin_config.indent_blankline')
require('plugin_config.gitsigns')
require('plugin_config.telescope')
require('plugin_config.nvim_treesitter')
require('plugin_config.lsp')
require('plugin_config.floaterm')
